---
- name: actualizacion 
  hosts: "{{ nodo }}"
  become: true
  tasks:
    - name: actualizacion OS
      ansible.builtin.yum:
        name: '*'
        state: latest

#    - name: httpd service enabled
#      ansible.builtin.service:
#        name: httpd
#        enabled: true
#        state: started
