---
- name: setup apache
  hosts: "{{ nodo }}"
  become: true
  tasks:
    - name: httpd installed
      ansible.builtin.yum:
        name: *
        state: latest

#    - name: httpd service enabled
#      ansible.builtin.service:
#        name: httpd
#        enabled: true
#        state: started
