---
- name: Map network drive on Windows
  hosts: "{{ nodo }}"
  vars:
    user: "{{ ansible_user }}"
    pass: "{{ ansible_pass }}"
    host: "{{ winhost }}"
  tasks:
    - name: Map network drive
      win_command: |
        net use Z: //"{{ host }}"/shared /user:""{{ user }}" "{{ pass }}"
