---
- name: Map network drive on Windows
  hosts: "{{ nodo }}"
  vars:
    user01: "{{ _user }}"
    pass01: "{{ _pass }}"
    host: "{{ winhost }}"
  tasks:
    - name: Map network drive
      win_command: |
        net use Z: \\"{{ host }}"\shared /user: "{{ user01 }}" "{{ pass01 }}"
