---
- name: Map network drive on Windows
  hosts: "{{ nodo }}"
  vars:src: c:\Temp\config.txt
        dest: z:\config.txt
      
    user01: "{{ _user }}"
    pass01: "{{ _pass }}"
    host: "{{ winhost }}"
  tasks:
    - name: Map network drive
      win_shell: |
        net use Z: "{{ host }}" /user:"{{ user01 }}" "{{ pass01 }}" /persistent:yes

    - name: Copy a single file where the source is on the remote host
       win_shell: |
        copy c:\temp\config.txt z:\        
