---
- name: Map network drive on Windows
  hosts: "{{ nodo }}"
  gather_facts: no
  vars:      
    user01: "{{ _user }}"
    pass01: "{{ _pass }}"
    host: "{{ winhost }}"
  tasks:
    - name: Map network drive
      win_command: |
        net use Z: {{ host }} /user:{{ user01 }} {{ pass01 }} /persistent:yes

#    - name: Copy a single file where the source is on the remote host
#      win_command: |
#        copy c:\temp\config.txt  z:\        
