---
- name: Map network drive on Windows
  hosts: "{{ nodo }}"
  gather_facts: no
  become: yes
  vars:      
    user01: "{{ _user }}"
    pass01: "{{ _pass }}"
  tasks:
    - name: Create mapped drive with credentials and save the username and password
      block:
        - name: Save the network credentials required for the mapped drive
          community.windows.win_credential:
            name: "WIN-8HT3HSM6UE5"
            type: domain_password
            username: "{{ user01 }}"
            secret: "{{ pass01 }}"
            state: present

        - name: Create a mapped drive that requires authentication
          community.windows.win_mapped_drive:
            letter: Z
            path: \\WIN-8HT3HSM6UE5\shared
            state: present
      rescue:
        - name: Cleanup credentials if mapping fails
          community.windows.win_credential:
            name: "WIN-8HT3HSM6UE5"
            type: domain_password
            state: absent
