---
- name: Obtener información de los nodos de un pool en F5
  hosts: f5
  gather_facts: no
  connection: local
  tasks:
    - name: Listar nodos de un pool
      bigip_pool_member:
        f5_hostname: "{{ bigip_host}}"
        f5_username: "{{ bigip_username }}"
        f5_password: "{{ _f5_password_ }}"
        f5_port: "{{ pool_name }}"
        name: "{{ pool_name }}"
        state: present
      register: pool_members

    - name: Mostrar información de los nodos del pool
      debug:
        msg: "{{ pool_members.members }}"
